name: CI/CD Pipeline

# Trigger the workflow on every to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
jobs:
  build-and-push:
    # Run the job on a fresh Ubuntu server provided by GitHub
    runs-on: ubuntu-latest

    environment:
      name: production

    # Grant permissions for the job to write to the GitHub Container Registry
    permissions:
      contents: read
      packages: write

    steps:
      # ----- CI PHASE -----
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Download Go Modules
        run: go mod download

      - name: Vendor dependencies
        run: go mod vendor

      - name: Run Go Tests
        run: go test ./...

      # ----- BUILD & PUSH -----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          timeout: 1000s
          host: ${{ secrets.SERVER_HOST }}     # e.g., '123.45.67.89'
          username: ${{ secrets.SERVER_USER }} # e.g., 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's private SSH key
          script: |
            set -e # Stop script immediately on error

            # 1. Setup Directory
            if [ ! -d "repoflow-backend/.git" ]; then
              echo "Repository not found or not a git repo â€” cloning fresh copy..."
              sudo rm -rf repoflow
              # If your repo is public:
              git clone https://github.com/regysaputra/repoflow-backend.git
              # If private, use a token (ensure TOKEN_GITHUB is set as secret)
              # git clone https://$GITHUB_ACTOR:$TOKEN_GITHUB@github.com/regysaputra/repoflow.git
            fi
            cd repoflow-backend
            git fetch origin main
            git reset --hard origin/main

            # 2. Setup Environment Variables
            echo "Creating .env file..."
            cat <<EOF > .env
            R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}
            R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}
            R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}
            R2_BUCKET=${{ secrets.R2_BUCKET }}
            EOF

            # 4. Pull Latest Images
            echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull app

            # 6. Restart Services
            echo "ðŸš€ Restarting services..."
            docker compose down --remove-orphans

            # Start App
            docker compose up -d app

            echo "Deployment Success!"